spring.application.name=muzi-music-api
#db mysql
spring.datasource.url=jdbc:mysql://localhost:3306/muzi-music
spring.datasource.username=root
spring.datasource.password=12345678
#jpa
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
#app properties
com.ahuynh.jwtSecret=210d3d27605d0ee737952294265400a7cba109746afacd84b9cb0139bf6b7e3a
com.ahuynh.jwtExp=36000000
#email
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=ahuynh359@gmail.com
spring.mail.password=cmciifspkcknjhmn
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

server.servlet.context-path=/api/v1
cors.allowedOrings=*
#firebase
firebase.bucket-name=app
firebase.image-url=https://storage.googleapis.com/${firebase.bucket-name}/%s